import {
  ANALYST_MODELS,
  DEAD_CODE_MODELS,
  DOCSTRING_MODELS,
  ERROR_EXPLAIN_MODELS,
  MODELS_BY_TASK,
  NAMING_HELPER_MODELS,
  PERFORMANCE_HINT_MODELS,
  TRANSLATE_MODELS,
  TYPE_HINTS_MODELS,
} from '@/lib/router/models'
import type { SectionDef } from './types'

export const CONTEXT_DIVISOR = 1024
export const CUSTOM_VALUE = '__custom__'

export const SECTIONS: SectionDef[] = [
  {
    accent: 'border-primary/40',
    configKey: 'analystModel',
    group: 'infrastructure',
    id: 'analyst',
    models: ANALYST_MODELS,
    selectionHint: 'Pick fast + reliable JSON output. Analyst runs on every request.',
    subtitle: 'Runs first: language detection, framework detection, and diff analysis.',
    title: 'Analyst',
  },
  {
    accent: 'border-border/70',
    configKey: 'explainModel',
    group: 'analysis',
    id: 'explain',
    models: MODELS_BY_TASK.explain,
    selectionHint: 'Prioritize instruction following and long context for full-file explanations.',
    subtitle: 'Code explanation and technical documentation.',
    title: 'Explain Code',
  },
  {
    accent: 'border-border/70',
    configKey: 'errorExplainModel',
    group: 'analysis',
    id: 'error-explain',
    models: ERROR_EXPLAIN_MODELS,
    selectionHint: 'Prioritize instruction-following models for clear root-cause explanations.',
    subtitle: 'Root-cause analysis and numbered fix steps for error messages.',
    title: 'Error Explain',
  },
  {
    accent: 'border-border/70',
    configKey: 'performanceHintModel',
    group: 'analysis',
    id: 'performance-hint',
    models: PERFORMANCE_HINT_MODELS,
    selectionHint: 'Prefer coder models with larger context for thorough optimization analysis.',
    subtitle: 'Advisory bullet list of non-breaking performance optimization suggestions.',
    title: 'Performance Hint',
  },
  {
    accent: 'border-border/70',
    configKey: 'deadCodeModel',
    group: 'analysis',
    id: 'dead-code',
    models: DEAD_CODE_MODELS,
    selectionHint: 'Prefer coder models for accurate detection of unused symbols.',
    subtitle: 'Identifies unused imports, unreachable code, and redundant variables.',
    title: 'Dead Code',
  },
  {
    accent: 'border-border/70',
    configKey: 'namingHelperModel',
    group: 'analysis',
    id: 'naming-helper',
    models: NAMING_HELPER_MODELS,
    selectionHint: 'Instruction-following models produce cleaner before → after rename lists.',
    subtitle: 'Structured before → after rename list with one-line rationale per entry.',
    title: 'Naming Helper',
  },
  {
    accent: 'border-border/70',
    configKey: 'testModel',
    group: 'generation',
    id: 'test',
    models: MODELS_BY_TASK.test,
    selectionHint: 'Prioritize code-specialist models for stronger edge-case coverage.',
    subtitle: 'Unit and integration test generation.',
    title: 'Generate Tests',
  },
  {
    accent: 'border-border/70',
    configKey: 'refactorModel',
    group: 'generation',
    id: 'refactor',
    models: MODELS_BY_TASK.refactor,
    selectionHint: 'Prefer coder models with larger context to avoid truncating full files.',
    subtitle: 'Cleanup, idiomatic rewrites, and structural code changes.',
    title: 'Refactor',
  },
  {
    accent: 'border-border/70',
    configKey: 'commitModel',
    group: 'generation',
    id: 'commit',
    models: MODELS_BY_TASK.commit,
    selectionHint: 'Small instruction-following models are usually enough for commit summaries.',
    subtitle: 'Conventional commit message generation from diffs.',
    title: 'Write Commit',
  },
  {
    accent: 'border-border/70',
    configKey: 'docstringModel',
    group: 'generation',
    id: 'docstring',
    models: DOCSTRING_MODELS,
    selectionHint: 'Instruction-following models produce accurate, complete documentation.',
    subtitle: 'Add or update documentation comments without changing any logic.',
    title: 'Docstring',
  },
  {
    accent: 'border-border/70',
    configKey: 'typeHintsModel',
    group: 'generation',
    id: 'type-hints',
    models: TYPE_HINTS_MODELS,
    selectionHint: 'Prefer coder models for accurate type inference without logic changes.',
    subtitle: 'Add type annotations to parameters and return values without changing logic.',
    title: 'Type Hints',
  },
  {
    accent: 'border-blue-500/40',
    configKey: 'translateModel',
    group: 'language',
    id: 'translate',
    models: TRANSLATE_MODELS,
    selectionHint: 'Use dedicated translation models unless you need in-block code translation.',
    subtitle: 'Translation to 37 languages. Code blocks remain unchanged by default.',
    title: 'Translation',
  },
]
