import type { ModelOption, ModelRuntime, TaskType } from '../types'
import { ANALYST_MODELS, DEFAULT_ANALYST_MODEL } from './analyst'
import {
  ANALYST_MODELS_CLOUD,
  DEFAULT_ANALYST_MODEL_CLOUD,
  DEFAULT_MODELS_CLOUD,
  DEFAULT_TRANSLATE_MODEL_CLOUD,
  MODELS_BY_TASK_CLOUD,
  TRANSLATE_MODELS_CLOUD,
} from './cloud'
import { COMMIT_MODELS, DEFAULT_COMMIT_MODEL } from './commit'
import { DEAD_CODE_MODELS, DEFAULT_DEAD_CODE_MODEL } from './dead-code'
import { DEFAULT_DOCSTRING_MODEL, DOCSTRING_MODELS } from './docstring'
import { DEFAULT_ERROR_EXPLAIN_MODEL, ERROR_EXPLAIN_MODELS } from './error-explain'
import { DEFAULT_EXPLAIN_MODEL, EXPLAIN_MODELS } from './explain'
import { DEFAULT_NAMING_HELPER_MODEL, NAMING_HELPER_MODELS } from './naming-helper'
import { DEFAULT_PERFORMANCE_HINT_MODEL, PERFORMANCE_HINT_MODELS } from './performance-hint'
import { DEFAULT_REFACTOR_MODEL, REFACTOR_MODELS } from './refactor'
import {
  ANALYST_MODELS_SMALL,
  DEFAULT_ANALYST_MODEL_SMALL,
  DEFAULT_MODELS_SMALL,
  DEFAULT_TRANSLATE_MODEL_SMALL,
  MODELS_BY_TASK_SMALL,
  TRANSLATE_MODELS_SMALL,
} from './small'
import { DEFAULT_TEST_MODEL, TEST_MODELS } from './test'
import { DEFAULT_TRANSLATE_MODEL, TRANSLATE_MODELS } from './translate'
import { DEFAULT_TYPE_HINTS_MODEL, TYPE_HINTS_MODELS } from './type-hints'

export type { ModelOption } from '../types'

export {
  ANALYST_MODELS,
  ANALYST_MODELS_CLOUD,
  ANALYST_MODELS_SMALL,
  COMMIT_MODELS,
  DEAD_CODE_MODELS,
  DOCSTRING_MODELS,
  ERROR_EXPLAIN_MODELS,
  EXPLAIN_MODELS,
  NAMING_HELPER_MODELS,
  PERFORMANCE_HINT_MODELS,
  REFACTOR_MODELS,
  TEST_MODELS,
  TRANSLATE_MODELS,
  TRANSLATE_MODELS_CLOUD,
  TRANSLATE_MODELS_SMALL,
  TYPE_HINTS_MODELS,
}

export {
  DEFAULT_ANALYST_MODEL,
  DEFAULT_ANALYST_MODEL_CLOUD,
  DEFAULT_ANALYST_MODEL_SMALL,
  DEFAULT_COMMIT_MODEL,
  DEFAULT_DEAD_CODE_MODEL,
  DEFAULT_DOCSTRING_MODEL,
  DEFAULT_ERROR_EXPLAIN_MODEL,
  DEFAULT_EXPLAIN_MODEL,
  DEFAULT_NAMING_HELPER_MODEL,
  DEFAULT_PERFORMANCE_HINT_MODEL,
  DEFAULT_REFACTOR_MODEL,
  DEFAULT_TEST_MODEL,
  DEFAULT_TRANSLATE_MODEL,
  DEFAULT_TRANSLATE_MODEL_CLOUD,
  DEFAULT_TRANSLATE_MODEL_SMALL,
  DEFAULT_TYPE_HINTS_MODEL,
}

export const MODELS_BY_TASK: Record<TaskType, ModelOption[]> = {
  commit: COMMIT_MODELS,
  'dead-code': DEAD_CODE_MODELS,
  docstring: DOCSTRING_MODELS,
  'error-explain': ERROR_EXPLAIN_MODELS,
  explain: EXPLAIN_MODELS,
  'naming-helper': NAMING_HELPER_MODELS,
  'performance-hint': PERFORMANCE_HINT_MODELS,
  refactor: REFACTOR_MODELS,
  test: TEST_MODELS,
  'type-hints': TYPE_HINTS_MODELS,
}

export const DEFAULT_MODELS: Record<TaskType, string> = {
  commit: DEFAULT_COMMIT_MODEL,
  'dead-code': DEFAULT_DEAD_CODE_MODEL,
  docstring: DEFAULT_DOCSTRING_MODEL,
  'error-explain': DEFAULT_ERROR_EXPLAIN_MODEL,
  explain: DEFAULT_EXPLAIN_MODEL,
  'naming-helper': DEFAULT_NAMING_HELPER_MODEL,
  'performance-hint': DEFAULT_PERFORMANCE_HINT_MODEL,
  refactor: DEFAULT_REFACTOR_MODEL,
  test: DEFAULT_TEST_MODEL,
  'type-hints': DEFAULT_TYPE_HINTS_MODEL,
}

export const MODELS_BY_TASK_BY_RUNTIME: Record<ModelRuntime, Record<TaskType, ModelOption[]>> = {
  cloud: MODELS_BY_TASK_CLOUD,
  local: MODELS_BY_TASK,
  small: MODELS_BY_TASK_SMALL,
}

export const DEFAULT_MODELS_BY_RUNTIME: Record<ModelRuntime, Record<TaskType, string>> = {
  cloud: DEFAULT_MODELS_CLOUD,
  local: DEFAULT_MODELS,
  small: DEFAULT_MODELS_SMALL,
}

export const ANALYST_MODELS_BY_RUNTIME: Record<ModelRuntime, ModelOption[]> = {
  cloud: ANALYST_MODELS_CLOUD,
  local: ANALYST_MODELS,
  small: ANALYST_MODELS_SMALL,
}

export const DEFAULT_ANALYST_MODEL_BY_RUNTIME: Record<ModelRuntime, string> = {
  cloud: DEFAULT_ANALYST_MODEL_CLOUD,
  local: DEFAULT_ANALYST_MODEL,
  small: DEFAULT_ANALYST_MODEL_SMALL,
}

export const TRANSLATE_MODELS_BY_RUNTIME: Record<ModelRuntime, ModelOption[]> = {
  cloud: TRANSLATE_MODELS_CLOUD,
  local: TRANSLATE_MODELS,
  small: TRANSLATE_MODELS_SMALL,
}

export const DEFAULT_TRANSLATE_MODEL_BY_RUNTIME: Record<ModelRuntime, string> = {
  cloud: DEFAULT_TRANSLATE_MODEL_CLOUD,
  local: DEFAULT_TRANSLATE_MODEL,
  small: DEFAULT_TRANSLATE_MODEL_SMALL,
}

export { OLLAMA_BASE_URL_DEFAULT } from '../ollama-defaults'
